secondstime = int(input("how seconds :"))
print("day: " + str(secondstime//86400))
print("hours: " + str(secondstime//3600%24))
print("minutes:" + str(secondstime//60%60))
print("seconds" + str(secondstime%60))